Features/posts
ApiTreeCZ/alda-cms pull request #6
Opened 2018-07-30 14:18 UTC by jakubjirkal

CRUD funkční.

- do budoucna pár změn na vzhledu -> pokud je moc příspěvků, překrývají se divně s dolní lištou

- nevím proč, ale handleOnClickDelete/Update občas zlobí -> pokud k nim dám console.log, stejně se nezavolá -> předpokládám že je to chyba v nastavení serveru nebo to můj notebook prostě nezvládá

2018-07-30 19:31 UTC, adostal requested changes
Zapsal jsem par pripominek. Prosel jsem cca 50% souboru.
Jinak za me super prace. Na prvni pokus vazne skvele.

2018-07-30 19:31 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +    tempPost: Post;
Zkus se podivat jak funguje v TS objekt Pick a Partial.
Priklad:
```typescript
inteface State {
 tempPost: Partial<Pick<Post, 'id'>>
}
```
Jinak bych to pojmenoval jinak, nez tempPost.

2018-07-30 19:31 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +    constructor(props: any) {
Tady by nemelo byt any, ale typ: WithAdminProps

2018-07-30 19:31 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +            tempPost: {id: -1, title: '', content: '', timeAndDate: ''},
Tohle resi predchozi komentar Pick<Partial ...

2018-07-30 19:31 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +        const temp: Post[] = [
Promennou, ktera je pak navratovou hodnotou z metody je lepsi pojmenovavat result nez temp.

2018-07-30 19:31 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +        this.setState({tempPost: {id: -1, title: '', content: '', timeAndDate: ''}});
Viz komentar s Pick a Partial

2018-07-30 19:31 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +    handleOnClickDelete = (i: any) => () => {
Typ any je malo, urcite je konkretniho datoveho typu (number)

2018-07-30 19:31 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +        this.setState({posts: this.state.posts.filter((e) => e.id !== +i)});
Proc je pred promennou i ono plus?

2018-07-30 19:31 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +        this.setState({dialogOpened: false});
Muzes oboji napsat do jednoho setState:
this.setState({x: 1, c: 5, ....})

2018-07-30 19:31 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +    handleTitleChange = (event: any) => {
Pro event existuje datovy typ v knihovne React. Zkus dohledat

2018-07-31 15:46 UTC, adostal requested changes

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +import MoreVertIcon from '@material-ui/icons/MoreVert';
Tohle se dá přepsat jako:
```typescript
import {MoreVert as MoreVertIcon, Delete as DeleteIcon} from '@material-ui/icons';
```

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +    timeAndDate: string;
Existuje datovy typ Date

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +    timeAndDate: string;
Navic je asi lepsi mit datum vytvoreni a datum zmeny. Tedy: created a updated

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +interface CreatePost extends Pick<Post, 'title' | 'content'> {}
Jeste se podivej, ze bys tady mohl pridat Partial, tedy:
```typescript
interface CreatePost extends Partial<Pick<Post, 'title' | 'content'>> {}
```
Vysledkem je, ze title i content muzou byt undefined.

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +            currentPost: {title: '', content: ''},
Diky partial nemusi byt title ci content inizializovan zde

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +    updatingId: number;
UpdatingId nemusi vzdy existovat. Proto lze napsat takto:
```typescript
updatingId?: number
```
Cimz padem updating muze byt undefined a nemusi se inicializovat

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +            updatingId: -1,
Diky otazniku u definice, muze byt undefined a nemusi se inicializovat

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +    getFakeState = () => {
Ten fake state dej mimo komponentu, nekam nad ni, at to pak lepe muzeme refactorovat

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +            this.setState({
Tohle neni uplne dobre, protoze v metode find mutujes puvodni objekt.

Kopie:
```typescript
const user = {id: 1, firstName: 'Pepa', lastName: 'Zdepa'};
const copyUser = {...user, lastName: 'Novak'};
```

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +            this.setState({
Tady je treba ukazka kodu, jak editovat prvky v poli:
```typescript
return users.map((user) => (user.id === id) ? {...user, firstName: 'Novakl'} : user);
```

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +            const foo: Post = {
Muzes si tenhle kod trochu zkratit (syntax sugar):
```typescript
const id: number = this.state.posts.length === 0 ? 0 : this.state.posts[this.state.posts.length - 1].id + 1;
const {currentPost: {title, content}} = this.state;
// toto 
const post: Post = {id: id, title: title, content: content, timeAndDate: ...};
// prepsat lze takto
const post: Post = {id, title, content, timeAndDate: ...};
```

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +                        <CardHeader title={post.title} subheader={post.timeAndDate + ' id:' + post.id} />
Existuje string interpolace:
```jsx
<CardHeader title={post.title} subheader={`${post.timeAndDate}id:${post.id}`} />
```

2018-07-31 15:46 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +    getTimeAndDateString = () => {
Toto nepotrebujes. Uloz do modelu Date pomoci new Date(). To, jak se pak onen datum zobrazi je spise o formatovani datumu. Je tam knihovna react-int, ktera ma komponenty pro zobrazeni datumu z objektu Date.

2018-07-31 16:45 UTC, jakubjirkal commented on client/admin/posts/components/PostsIndexPage.tsx
> +            const foo: Post = {
Nepochopil jsem jak. Zkoušel jsem ale hlásilo chyby.

2018-08-03 19:45 UTC, adostal requested changes

2018-08-03 19:45 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +} from '../../../../node_modules/@material-ui/core';
Tady oprav ten import na: from '@material-ui/core';

2018-08-10 13:09 UTC, adostal requested changes

2018-08-10 13:09 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +    createdAt: Date;
Auditni informace musime sjednotit, maji je i ostatni. V sobotu si rekneme vice

2018-08-10 13:09 UTC, adostal commented on client/admin/posts/components/PostsIndexPage.tsx
> +const getFakeState = () => {
Zkus ten stav, ktery komponente predavas, predat pres props pomoci patternu HOC. Pote prepiseme jen implementaci onoho HOC vuci serveru a zbytek se nebude muset menit.

2022-05-10 11:16 UTC, closed without merging